# This file is a template, and might need editing before it works on your project.
# The following script will work for any project that can be built from command line by msbuild
# It uses powershell shell executor, so you need to add the following line to your config.toml file
# (located in gitlab-runner.exe directory):
#   shell = "powershell"
#
# The script is composed of 3 stages: build, test and deploy.  
#
# The build stage restores NuGet packages and uses msbuild to build the exe and msi
# One major issue you'll find is that you can't build msi projects from command line
# if you use vdproj.  There are workarounds building msi via devenv, but they rarely work
# The best solution is migrating your vdproj projects to WiX, as it can be build directly 
# by msbuild.
#
# The test stage runs nunit from command line against Test project inside your solution
# It also saves the resulting TestResult.xml file
#
# The deploy stage copies the exe and msi from build stage to a network drive
# You need to have the network drive mapped as Local System user for gitlab-runner service to see it
# The best way to persist the mapping is via a scheduled task (see: https://stackoverflow.com/a/7867064/1288473),
# running the following batch command: net use P: \\x.x.x.x\Projects /u:your_user your_pass /persistent:yes


# place project specific paths in variables to make the rest of the script more generic

stages:
  - build
  - deploy
  
cache:
    paths:
    - WebSite/node_modules/
    - ServiceSite/packages/

build_job:
  stage: build

  script:

  - echo "Restoring NuGet Packages..." 

  - E:\nuget\nuget.exe restore "ServiceSite\SyTemplater.sln" 

  - echo "webapi Solution Build..."
  
  - chcp 850

  - C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Community\MSBuild\15.0\Bin\msbuild.exe /p:Configuration=Release /p:Platform="Any CPU" /maxcpucount /nologo /property:Configuration=Release /t:rebuild "ServiceSite\SyTemplater.sln"
  
  - echo "WebSite Build..."
  
  - cd website
  
  - npm install

  - npm audit fix

  - npm run build
  
  tags: 

  except:

  - tags

deploy:
    stage: deploy
    
    script:

    - echo "webapi Solution deploy..."

    - chcp 850

    - C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Community\MSBuild\15.0\Bin\msbuild.exe ServiceSite\WebApi\SeaSky.SyTemplater.WebApi.csproj "/P:DeployOnBuild=True;PublishProfile=FolderProfile" /p:Configuration=Release
    
    - cd website

    - npm run build:deploy
    
    only:
      
    - develop
    
    tags:
      
    # - deploy
  